# Generated by Django 5.2.4 on 2025-07-24 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Décrivez brièvement votre tâche', max_length=200, verbose_name='Titre de la tâche')),
                ('description', models.TextField(blank=True, help_text='Ajoutez plus de détails si nécessaire', null=True, verbose_name='Description détaillée')),
                ('status', models.CharField(choices=[('todo', 'À faire'), ('doing', 'En cours'), ('done', 'Terminé')], default='todo', max_length=10, verbose_name='Statut')),
                ('priority', models.CharField(choices=[('low', 'Basse'), ('medium', 'Moyenne'), ('high', 'Haute'), ('urgent', 'Urgente')], default='medium', max_length=10, verbose_name='Priorité')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name="Date d'échéance")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Tâche',
                'verbose_name_plural': 'Tâches',
                'ordering': ['-created_at'],
            },
        ),
    ]
